---
permalink: rhel-install/concept-unsupported-features-for-wfa-on-linux.html 
sidebar: sidebar 
keywords: oncommand workflow automation, known, limitations 
summary: 'OnCommand Workflow Automation (WFA) 5.0 inclut certaines limites et fonctionnalités non prises en charge que vous devez connaître avant d"installer et de configurer WFA.' 
---
= Limitations connues de OnCommand Workflow Automation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation (WFA) 5.0 inclut certaines limites et fonctionnalités non prises en charge que vous devez connaître avant d'installer et de configurer WFA.

*Authentification LDAP*

* Vous pouvez utiliser uniquement le serveur LDAP (Lightweight Directory Access Protocol) de Microsoft Active Directory pour l'authentification LDAP.
* Vous ne devez pas utiliser un nom d'utilisateur LDAP faisant partie d'une structure hiérarchique de plusieurs domaines pour l'authentification ou la notification.


[NOTE]
====
Microsoft Active Directory Lightweight Directory Services (AD LDS) n'est pas pris en charge.

====
*Types de sources de données WFA*

Les types de sources de données Active IQ Data Center Manager 6.0, 6.1 et 6.2 sont obsolètes dans la version WFA 4.1, et ces types de sources de données ne seront pas pris en charge dans les versions ultérieures.

* WFA installé sous Linux*

* Les contenus certifiés de Data ONTAP fonctionnant en 7-mode ne sont pas disponibles pour le moment.
* Les commandes qui incluent uniquement du code PowerShell ne sont pas compatibles avec Linux.
* Les commandes certifiées pour 7-mode et VMware ne sont actuellement pas portées en Perl, et ne sont donc pas compatibles avec Linux.

