---
permalink: rhel-install/reference-system-requirements-for-oncommand-workflow-automation-linux.html 
sidebar: sidebar 
keywords: oncommand workflow automation, system, requirements, install, hardware, requirements, install, wfa 
summary: 'Avant d"installer WFA, vous devez connaître la configuration matérielle et logicielle requise pour OnCommand Workflow Automation (WFA).' 
---
= Configuration système requise pour l'installation de OnCommand Workflow Automation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'installer WFA, vous devez connaître la configuration matérielle et logicielle requise pour OnCommand Workflow Automation (WFA).



== Configuration matérielle requise pour l'installation de WFA

Le tableau suivant répertorie la configuration matérielle minimale requise et les spécifications matérielles recommandées pour le serveur WFA.

[cols="3*"]
|===
| Composant | Configuration minimale requise | Spécifications recommandées 


 a| 
CPU
 a| 
2.27 GHz ou plus, 2 cœurs, 64 bits
 a| 
2.27 GHz ou plus, 2 cœurs, 64 bits



 a| 
RAM
 a| 
4 Go
 a| 
8 Go



 a| 
Espace disque disponible
 a| 
5 GO
 a| 
20 GO

|===
[NOTE]
====
Si vous installez WFA sur une machine virtuelle, il est recommandé de réserver la mémoire et le processeur nécessaires afin que cette dernière dispose de ressources suffisantes. Le programme d'installation ne vérifie pas la vitesse de la CPU.

====


== Configuration logicielle requise pour l'installation de WFA

Le tableau suivant répertorie toutes les versions du système d'exploitation compatibles avec le serveur WFA.

[cols="2*"]
|===
| Système d'exploitation | Version 


 a| 
Red Hat Enterprise Linux
 a| 
systèmes d'exploitation 6.5, 7.0, 7.1 64 bits, 7.2, 7.3 et 7.4



 a| 
CentOS
 a| 
7.1, 7.2 et 7.3

|===
[NOTE]
====
WFA doit être installé sur des machines virtuelles ou physiques dédiées. Vous ne devez pas installer d'autres applications sur le serveur qui exécute WFA.

====


== Autres logiciels minimum requis

* L'un des navigateurs pris en charge suivants :
+
** Mozilla Firefox
** Microsoft Internet Explorer
** Google Chrome


* La dernière version d'Adobe Flash Player pour votre navigateur
* Perl v5.10.1
+
Vous pouvez obtenir des informations sur les modules Perl qui doivent être installés à l'aide du `./WFA-version_number.bin -l` commande.



Pour plus d'informations, consultez la matrice d'interopérabilité.

*Informations connexes*

http://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^]
