---
permalink: rhel-install/task-restore-regular-the-oncommand-workflow-automation-database-and-configurations-linux.html 
sidebar: sidebar 
keywords: oncommand workflow automation, wfa, cli, restore 
summary: 'Vous pouvez effectuer une restauration régulière de la base de données OnCommand Workflow Automation (WFA) que vous avez sauvegardée précédemment à l"aide de l"interface de ligne de commandes. Lors d"une restauration régulière, vous ne pouvez restaurer que la base de données WFA.' 
---
= Restauration (régulière) de la base de données WFA à l'aide de l'interface de ligne de commande
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer une restauration régulière de la base de données OnCommand Workflow Automation (WFA) que vous avez sauvegardée précédemment à l'aide de l'interface de ligne de commandes. Lors d'une restauration régulière, vous ne pouvez restaurer que la base de données WFA.

.Ce dont vous avez besoin, 8217;ll
* Vous devez avoir créé une sauvegarde de la base de données WFA.
* Vous devez disposer d'informations d'identification admin ou Architect.


.Étapes
. À l'invite du shell, accédez au répertoire suivant sur le serveur WFA :
+
`WFA_install_location/wfa/bin`

+
`wfa_install_location` Est le répertoire d'installation de WFA.

. Restaurez la base de données WFA :
+
`wfa --restore --user=user_name [--password=password] [--location=path]`

+
** _user_name_ est le nom d'utilisateur de l'utilisateur admin ou architecte.
** _password_ est le mot de passe de l'utilisateur.
+
Si vous n'avez pas fourni le mot de passe, vous devez entrer le mot de passe lorsque vous y êtes invité.

** _path_ est le chemin complet du répertoire du fichier de restauration.


. Vérifiez que l'opération de restauration est réussie et que WFA est accessible.

