---
settings:
  name: OnCommand Workflow Automation 5.0
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentation OnCommand Workflow Automation 5.0
    url: "/index.html"
  - title: Notes de version
    url: "/reference-releasenotes.html"
  - section: rhel-install
  - section: windows-install
  - section: help
  - section: workflows
  - title: Mentions légales
    url: "/legal-notices.html"
