---
permalink: windows-install/task-back-up-oncommand-workflow-automation-using-powershell-script.html 
sidebar: sidebar 
keywords: back up, wfa, database, powershell, script 
summary: 'Si vous souhaitez sauvegarder fréquemment la base de données OnCommand Workflow Automation (WFA), vous pouvez utiliser le script PowerShell fourni avec le pack d"installation de WFA.' 
---
= Sauvegardez la base de données WFA à l'aide du script PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous souhaitez sauvegarder fréquemment la base de données OnCommand Workflow Automation (WFA), vous pouvez utiliser le script PowerShell fourni avec le pack d'installation de WFA.

.Ce dont vous avez besoin
Vous devez disposer des informations d'identification de l'utilisateur administrateur, des informations d'identification d'architecte ou des informations d'identification de l'utilisateur de sauvegarde.

.Description de la tâche
Pour plus d'informations, consultez la documentation REST.

. Ouvrez Windows PowerShell en tant qu'administrateur, puis sauvegardez la base de données WFA :
+
`<WFA_install_location\WFA\bin\Backup.ps1> -User user_name -Password password -Path backup_file_path`

+
** `WFA_install_location` Est le répertoire d'installation de WFA.
** _user_name_ est le nom d'utilisateur de l'utilisateur admin, de l'architecte ou de l'utilisateur de sauvegarde.
** _password_ est le mot de passe de l'utilisateur admin, architecte ou sauvegarde.
** `backup_file_path` est le chemin complet du répertoire du fichier de sauvegarde.
+

NOTE: Le fichier de sauvegarde est un fichier zip dont le nom est au format suivant : + `wfa_backup_servername_.zip`

** `wfa_backup_` est une partie fixe du nom du fichier, qui est le nom du serveur de sauvegarde.
** `servername` Est extrait de l'environnement du serveur Windows.
** `_.zip` est une partie fixe du nom de fichier. + *exemple* +
`C:\Program Files\NetApp\WFA\bin\Backup.ps1 -User backup -Password MyPassword123 -Path C:\WFA_backups\backup_10_08_12`
+
Une fois la sauvegarde terminée, le résultat suivant s'affiche : `C:\WFA_backups\backup_10__08_12\wfa_backup_myserver__.zip`



. *Facultatif:* Vérifiez que le fichier de sauvegarde a été créé à l'emplacement spécifié.

